Leucippus/Controllers/MatrixController.cs
using Leucippus.Models;
using LeuciShared;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Plotly.NET;


namespace Leucippus.Controllers
{
    public class MatrixController : Controller
    {
        public async Task<IActionResult> Index(string pdbcode = "")
        {
            try
            {
                ViewBag.Error = "";
                ViewBagMatrix.Instance.PdbCode = pdbcode;

                DensityMatrix dm = await DensitySingleton.Instance.getMatrix(ViewBagMatrix.Instance.PdbCode, ViewBagMatrix.Instance.Interp, 2, -1,2);
                if (DensitySingleton.Instance.NewMatrix)
                {
                    string[] first_three = DensitySingleton.Instance.FD.PA.getFirstThreeCoords();
                    ViewBagMatrix.Instance.CentralAtomStrucString = first_three[0];
                    ViewBagMatrix.Instance.LinearAtomStrucString = first_three[1];
                    ViewBagMatrix.Instance.PlanarAtomStrucString = first_three[2];
                }

                ViewBagMatrix.Instance.Info = dm.Info;
                ViewBagMatrix.Instance.EmCode = DensitySingleton.Instance.FD.EmCode;
                ViewBagMatrix.Instance.DensityType = DensitySingleton.Instance.FD.DensityType;

                ViewBag.PdbCode = ViewBagMatrix.Instance.PdbCode;
                ViewBag.EmCode = ViewBagMatrix.Instance.EmCode;
                ViewBag.Info = ViewBagMatrix.Instance.Info;
                ViewBag.EbiLink = ViewBagMatrix.Instance.EbiLink;
                ViewBag.DensityType = ViewBagMatrix.Instance.DensityType;
                ViewBag.Resolution = DensitySingleton.Instance.FD.Resolution;

                return View();
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }

        }

        public async Task<IActionResult> Plane(string pdbcode = "", int layer = -1, string plane = "", string planeplot = "")
        {
            try
            {
                ViewBag.Error = "";
                //https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_element_innerhtml            
                bool newCalcs = true;
                ViewBagMatrix.Instance.PdbCode = pdbcode;
                if (ViewBagMatrix.Instance.Refresh)
                {
                    ViewBagMatrix.Instance.SetCentral("", "", DensitySingleton.Instance.FD.PA, 0);
                    ViewBagMatrix.Instance.SetLinear("", "", DensitySingleton.Instance.FD.PA, 0);
                    ViewBagMatrix.Instance.SetPlanar("", "", DensitySingleton.Instance.FD.PA, 0);
                }

                ViewBagMatrix.Instance.Plane = plane;
                ViewBagMatrix.Instance.Layer = layer;
                ViewBagMatrix.Instance.PlanePlot = planeplot;

                DensityMatrix dm = await DensitySingleton.Instance.getMatrix(ViewBagMatrix.Instance.PdbCode, ViewBagMatrix.Instance.Interp, 2, -1,2);
                dm.calculatePlane(ViewBagMatrix.Instance.Plane, ViewBagMatrix.Instance.Layer);

                if (ViewBagMatrix.Instance.EmCode == "" && layer == -1 && plane == "")
                    newCalcs = false;

                ViewBagMatrix.Instance.EmCode = DensitySingleton.Instance.FD.EmCode;
                ViewBagMatrix.Instance.DensityType = DensitySingleton.Instance.FD.DensityType;

                ViewBag.MtxX = dm.MatA;
                ViewBag.MtxY = dm.MatB;
                ViewBag.MtxZ = dm.MatC;
                ViewBag.MtxV = dm.MatD;

                ViewBag.PdbCode = ViewBagMatrix.Instance.PdbCode;
                ViewBag.Plane = ViewBagMatrix.Instance.Plane;
                ViewBag.Layer = dm.Layer;
                ViewBag.LayerMax = dm.LayerMax - 1;
                ViewBag.MinV = dm.DMin;
                ViewBag.MaxV = dm.DMax;
                ViewBag.PlanePlot = ViewBagMatrix.Instance.PlanePlot;

                return View();
            }
            catch (Exception e)
            {
                ViewBag.Error = e.Message;
                return View();
            }

        }
        public async Task<IActionResult> Slice(
            string tabview = "A", // A=atoms,S=settgins,N=neighbour X=advanced
            string refresh_mode = "R", //V= viewbag only F = force
            string pdbcode = "",
            string c_xyz = "", string l_xyz = "", string p_xyz = "",
            string ca = "", string la = "", string pa = "", int atom_offset = 0,
            string denplot = "", string radplot = "", string lapplot = "",
            string denhue = "", string radhue = "", string laphue = "",
            string denbar = "", string radbar = "", string lapbar = "",
            double width = -1, int samples = -1, string interp = "",
            string valsd = "", double sdcap = -100, double sdfloor = -100,
            int Fos = 2, int Fcs = -1, int copies=3,string ydots = "N", string gdots = "N",
            int t1 = 0, int t2 = 0, int t3 = 0, int t4 = 0,
            string nav = "", double nav_distance = 0.1,
            double hover_min = 0, double hover_max = 0)
        {
            bool view_change = false;

            if (t1 + t2 + t3 + t4 > 0)//then this is a view only change
            {
                view_change = true;
            }

            // visual elements need to be set
            ViewBagMatrix.Instance.T1Display = "none";
            ViewBagMatrix.Instance.T2Display = "none";
            ViewBagMatrix.Instance.T3Display = "none";
            ViewBagMatrix.Instance.T5Display = "none";
            ViewBagMatrix.Instance.T4Display = "none";
            ViewBag.TabName = "Navigate";
            ViewBag.TabAClick = "inherit";
            ViewBag.TabSClick = "inherit";
            ViewBag.TabNClick = "inherit";
            ViewBag.TabMClick = "inherit";
            ViewBag.TabXClick = "inherit";
            ViewBag.TabAName = "none";
            ViewBag.TabSName = "none";
            ViewBag.TabNName = "none";
            ViewBag.TabMName = "none";
            ViewBag.TabXName = "none";

            if (view_change)//then this is a view only change
            {
                if (t1 == 1) //atoms
                {
                    ViewBag.TabView = "A";
                    ViewBag.TabName = "Navigate";
                    //refresh_mode = "F";
                }
                if (t2 == 1) //settings
                {
                    ViewBag.TabView = "S";
                    ViewBag.TabName = "Options";
                }
                if (t3 == 1) //neighbours
                {
                    ViewBag.TabView = "N";
                    //refresh_mode = "F";
                    ViewBag.TabName = "Neighbours";
                }
                if (t4 == 1)//advanced
                {
                    ViewBag.TabView = "X";
                    ViewBag.TabName = "Advanced";
                }

            }

            //we should make sure we have the correct block selected                            
            ViewBag.TabView = tabview;
            if (tabview == "A")
            {
                ViewBagMatrix.Instance.T1Display = "block";
                ViewBag.TabAClick = "none";
                ViewBag.TabAName = "contents";
                ViewBag.TabName = "Navigate";
            }
            else if (tabview == "N")
            {
                ViewBagMatrix.Instance.T3Display = "block";
                ViewBag.TabNClick = "none";
                ViewBag.TabNName = "contents";
                ViewBag.TabName = "Neighbours";
            }            
            else if (tabview == "S")
            {
                ViewBagMatrix.Instance.T2Display = "block";
                ViewBag.TabSClick = "none";
                ViewBag.TabSName = "contents";
                ViewBag.TabName = "Options";
            }
            else if (tabview == "X")
            {
                ViewBagMatrix.Instance.T4Display = "block";
                ViewBag.TabXClick = "none";
                ViewBag.TabXName = "contents";
                ViewBag.TabName = "Advanced";
            }



            try
            {
                ViewBag.Error = "";
                ViewBagMatrix.Instance.PdbCode = pdbcode;
                ViewBagMatrix.Instance.Interp = interp;
                ViewBagMatrix.Instance.setFoFc(Fos, Fcs);
                ViewBagMatrix.Instance.Copies = copies;
                ViewBagMatrix.Instance.DenPlot = denplot;
                ViewBagMatrix.Instance.RadPlot = radplot;
                ViewBagMatrix.Instance.LapPlot = lapplot;
                ViewBagMatrix.Instance.DenHue = denhue;
                ViewBagMatrix.Instance.RadHue = radhue;
                ViewBagMatrix.Instance.LapHue = laphue;
                ViewBagMatrix.Instance.DenBar = denbar;
                ViewBagMatrix.Instance.RadBar = radbar;
                ViewBagMatrix.Instance.LapBar = lapbar;
                ViewBagMatrix.Instance.Width = width;
                ViewBagMatrix.Instance.Samples = samples;
                ViewBagMatrix.Instance.ValSd = valsd;
                ViewBagMatrix.Instance.SdCap = sdcap;
                ViewBagMatrix.Instance.SdCap = Math.Round(ViewBagMatrix.Instance.SdCap, 2);
                ViewBagMatrix.Instance.SdFloor = sdfloor;
                ViewBagMatrix.Instance.SdFloor = Math.Round(ViewBagMatrix.Instance.SdFloor, 2);
                ViewBagMatrix.Instance.YellowDots = ydots;
                ViewBagMatrix.Instance.GreenDots = gdots;
                ViewBagMatrix.Instance.HoverMin = hover_min;
                ViewBagMatrix.Instance.HoverMax = hover_max;
                ViewBagMatrix.Instance.NavDistance = nav_distance;

                if (ViewBagMatrix.Instance.Refresh && c_xyz == "" && l_xyz == "" && p_xyz == "")
                {
                    ViewBagMatrix.Instance.SetCentral("", "", DensitySingleton.Instance.FD.PA, atom_offset);

Leucippus/Controllers/PlotlyController.cs
using ChartDirector;
using Leucippus.Models;
using LeuciShared;
using Microsoft.AspNetCore.Mvc;
using ScottPlot;
using System.Collections.Generic;
using System.Numerics;
using static Plotly.NET.StyleParam;


namespace Leucippus.Controllers
{
    public class PlotlyController : Controller
    {
        //ElectronDensity ed = new ElectronDensity("");
        //string _pdbcode = "";
        //string _plane = "";
        //int _layer = 0;
        public async Task <IActionResult> Index(string pdbcode = "")
        {
            DensityMatrix dm = await DensitySingleton.Instance.getMatrix(pdbcode);
            if (!MatrixServer.Instance.init)
            {
                pdbcode = "6eex";
                await MatrixServer.Instance.setPdbCode("6eex");                
            }
            else if (pdbcode == "")
            {                
                pdbcode = MatrixServer.Instance.PdbCode;
            }
            else if (MatrixServer.Instance.PdbCode != pdbcode)
            {
                await MatrixServer.Instance.setPdbCode(pdbcode);                
            }

            ViewBag.PdbCode = MatrixServer.Instance.ed.PdbCode;
            ViewBag.Info = MatrixServer.Instance.ed.Info;
            ViewBag.EbiLink = MatrixServer.Instance.ed.EbiLink;

            return View();            
        }
        
        public async Task<IActionResult> Matrix(string pdbcode = "", int layer = -1, string plane="")
        {            
            //https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_element_innerhtml            
            bool newCalcs = true;
            
            if (!MatrixServer.Instance.init)
            {
                pdbcode = "6eex";
                layer = 0;
                plane = "XY";
                await MatrixServer.Instance.setPdbCode("6eex");                
                newCalcs = true;

            }
            else
            {
                if (pdbcode == "")
                    pdbcode = MatrixServer.Instance.PdbCode;
                if (plane == "")
                    plane = MatrixServer.Instance.ed.Plane;
                if (layer == -1)
                    layer = MatrixServer.Instance.ed.Layer;
            }
            if (pdbcode == "" && layer == -1 && plane == "")            
                newCalcs = false;
                                                                                        
            if (MatrixServer.Instance.PdbCode != pdbcode)
            {
                await MatrixServer.Instance.setPdbCode(pdbcode);
                newCalcs = true;
            }
            else
            {
                if (MatrixServer.Instance.ed.Layer != layer)
                {
                    newCalcs = true;
                    MatrixServer.Instance.ed.Layer = layer;
                }
                if (MatrixServer.Instance.ed.Plane != plane)
                {
                    newCalcs = true;
                    MatrixServer.Instance.ed.Plane = plane;
                }
            }
            
            if (newCalcs)
            {
                MatrixServer.Instance.ed.calculateWholeLayer(plane, layer);                
            }            
            ViewBag.MtxX = MatrixServer.Instance.ed.MtxA;
            ViewBag.MtxY = MatrixServer.Instance.ed.MtxB;
            ViewBag.MtxZ = MatrixServer.Instance.ed.MtxC;
            ViewBag.MtxV = MatrixServer.Instance.ed.MtxD;
            ViewBag.PdbCode = MatrixServer.Instance.ed.PdbCode;            
            ViewBag.Plane = MatrixServer.Instance.ed.Plane;
            ViewBag.Layer = MatrixServer.Instance.ed.Layer;
            ViewBag.LayerMax = MatrixServer.Instance.ed.LayerMax - 1;
            ViewBag.MinV = MatrixServer.Instance.ed.MinV;
            ViewBag.MaxV = MatrixServer.Instance.ed.MaxV;
            return View();

        }
        public async Task<IActionResult> Slice(string pdbcode = "", 
            double cx = -1, double cy = -1, double cz = -1,
            double lx = -1, double ly = -1, double lz = -1, 
            double px = -1, double py = -1, double pz = -1)
        {
            bool recalc = true;
            if (!MatrixServer.Instance.init)
            {
                if (pdbcode == "")
                    pdbcode = "6eex";                
                await MatrixServer.Instance.setPdbCode(pdbcode);
                recalc = true;
            }
            else
            {
                if (pdbcode == "")
                    pdbcode = MatrixServer.Instance.PdbCode;
                if (pdbcode != MatrixServer.Instance.PdbCode)
                {
                    MatrixServer.Instance.PdbCode = pdbcode;
                    await MatrixServer.Instance.setPdbCode(pdbcode);
                    recalc = true;
                }
                if (cx == -1)
                {
                    cx = MatrixServer.Instance.ed.CX;
                    cy = MatrixServer.Instance.ed.CY;
                    cz = MatrixServer.Instance.ed.CZ;
                    lx = MatrixServer.Instance.ed.LX;
                    ly = MatrixServer.Instance.ed.LY;
                    lz = MatrixServer.Instance.ed.LZ;
                    px = MatrixServer.Instance.ed.PX;
                    py = MatrixServer.Instance.ed.PY;
                    pz = MatrixServer.Instance.ed.PZ;
                    recalc = false;
                }
                else
                {
                    MatrixServer.Instance.ed.CX = cx;
                    MatrixServer.Instance.ed.CY = cy;
                    MatrixServer.Instance.ed.CZ = cz;
                    MatrixServer.Instance.ed.LX = lx;
                    MatrixServer.Instance.ed.LY = ly;
                    MatrixServer.Instance.ed.LZ = lz;
                    MatrixServer.Instance.ed.PX = px;
                    MatrixServer.Instance.ed.PY = py;
                    MatrixServer.Instance.ed.PZ = pz;
                }
            }

            //if (MatrixServer.Instance.ed.SliceAxis.Length == 0)
                //recalc = true;
            if (recalc)
                MatrixServer.Instance.ed.getSlice();
            ViewBag.SliceDensity = MatrixServer.Instance.ed.SliceDensity;
            ViewBag.SliceRadiant = MatrixServer.Instance.ed.SliceRadiant;
            ViewBag.SliceLaplacian = MatrixServer.Instance.ed.SliceLaplacian;
            ViewBag.SliceAxis = MatrixServer.Instance.ed.SliceAxis;

            ViewBag.cx = MatrixServer.Instance.ed.CX;
            ViewBag.cy = MatrixServer.Instance.ed.CY;
            ViewBag.cz = MatrixServer.Instance.ed.CZ;
            ViewBag.lx = MatrixServer.Instance.ed.LX;
            ViewBag.ly = MatrixServer.Instance.ed.LY;
            ViewBag.lz = MatrixServer.Instance.ed.LZ;
            ViewBag.px = MatrixServer.Instance.ed.PX;
            ViewBag.py = MatrixServer.Instance.ed.PY;
            ViewBag.pz = MatrixServer.Instance.ed.PZ;

            ViewBag.PdbCode = MatrixServer.Instance.ed.PdbCode;


            

            return View();
        }

    }
}

Leucippus/Views/Plotly/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutDensity.cshtml";
}

<h1>Electron Density Matrix Explorer - @ViewBag.PdbCode</h1>
<hr />

@using (Html.BeginForm("Index", "Plotly", FormMethod.Post))
{
    <table cellpadding="0" cellspacing="0">
        <tr style="height:25%">
            <th colspan="1" align="center">Protein Structure</th>
        </tr>
        <tr style="height:30px;" />            
            <td>
                <span>
                PdbCode:
                    <input type="text" id="pdbcode" name="pdbcode" value=@ViewBag.PdbCode style="height:30px;" />
                    <input type="image" src="~/images/search.png" style="height:30px;vertical-align:text-bottom" />
                </span>
        </td>        
    </table>
}
<hr />
<div>
    Explore the structure with the top menu items <i>Slice</i> to look at real space contour slices, or <i>Matrix</i> to explore the raw matrix data.
</div>

<hr />
<div id="detes">
    <h3>Details about @ViewBag.PdbCode electron density</h3>
    <a href=@ViewBag.EbiLink>EBI Link to @ViewBag.PdbCode</a>
    <br />
    @Html.Raw(@ViewBag.Info)
</div>

Leucippus/Views/Plotly/Matrix.cshtml
@{
    ViewData["Title"] = "Matrix";
    Layout = "~/Views/Shared/_LayoutDensity.cshtml";
}

<h1>Raw Density Matrix - @ViewBag.PdbCode</h1>
<hr/>
<div>
<h5>Interactive matrix explorer - planes</h5>

@using (Html.BeginForm("Matrix", "Plotly", FormMethod.Post))
    {
        <table cellpadding="0" cellspacing="0"><!-- style="background-color:PowderBlue">-->
            <tr style="height:25%">
                <th colspan="1" align="center">Layer</th>
                <th>Click to choose plane</th>
                <th>Click to increment layer</th>
            </tr>            
            <tr style="height:25%">                
                <td>
                    <input type="text" id="layer" name="layer" align="center" value=@ViewBag.Layer>
                </td>
                <td>
                                @Html.ActionLink(
                            linkText: "XY Plane",
                            actionName: "Matrix",
                            controllerName: "Plotly",
                            routeValues: new {
                            pdbcode = @ViewBag.PdbCode,
                            plane = "XY",
                            layer = @ViewBag.Layer
                            },
                            htmlAttributes: null
                            )
                                <span> ~ </span>
                                @Html.ActionLink(
                            linkText: "YZ Plane",
                            actionName: "Matrix",
                            controllerName: "Plotly",
                            routeValues: new {
                            pdbcode = @ViewBag.PdbCode,
                            plane = "YZ",
                            layer = @ViewBag.Layer
                            },
                            htmlAttributes: null
                            )
                                <span> ~ </span>
                                @Html.ActionLink(
                            linkText: "ZX Plane",
                            actionName: "Matrix",
                            controllerName: "Plotly",
                            routeValues: new {
                            pdbcode = @ViewBag.PdbCode,
                            plane = "ZX",
                            layer = @ViewBag.Layer
                            },
                            htmlAttributes: null
                            )
                </td>
                <td>
                                @Html.ActionLink(
                            linkText: " - 1",
                            actionName: "Matrix",
                            controllerName: "Plotly",
                            routeValues: new {
                            pdbcode = @ViewBag.PdbCode,
                            plane = @ViewBag.Plane,
                            layer = @ViewBag.Layer - 1
                            },
                            htmlAttributes: null
                            )
                                <span> ~ </span>
                                @Html.ActionLink(
                            linkText: " + 1",
                            actionName: "Matrix",
                            controllerName: "Plotly",
                            routeValues: new {
                            pdbcode = @ViewBag.PdbCode,
                            plane = @ViewBag.Plane,
                            layer = @ViewBag.Layer + 1
                            },
                            htmlAttributes: null
                            )
                </td>
            </tr>            
            <tr><!-- style="height:25%;background-color:Crimson;">-->
                <td><input type="submit" value="Jump to"/></td>
                <td>Chosen plane= @ViewBag.Plane</td>
                <td>Chosen layer= @ViewBag.Layer / @ViewBag.LayerMax</td>
            </tr>
        </table>
    }
    
</div>
<br/>


<div>
    <div>
    <div>
        <div id="myCountour" style="width:40%"></div>
        </div>    
    <hr/>
    <div>
        <div id="myDiv" style="width:40%"></div>
        </div>    
    </div>
    </div>

<script>
    var jx = @Html.Raw(Json.Serialize(@ViewBag.MtxX));
    var jy = @Html.Raw(Json.Serialize(@ViewBag.MtxY));
    var jz = @Html.Raw(Json.Serialize(@ViewBag.MtxZ));    
    var jv = @Html.Raw(Json.Serialize(@ViewBag.MtxV));    
    var minv = @Html.Raw(Json.Serialize(@ViewBag.MinV));    
    var maxv = @Html.Raw(Json.Serialize(@ViewBag.MaxV));    
            
    var layoutH = {
        autosize: true,
        title: 'Electron density values in this plane'     
    };

    var traceH = {
    x: jz,
    type: 'histogram',
    nbinsx: 50,
    marker: {
        color: "Crimson",
        line: {
            color:  "Silver", 
            width: 1
        }
    }
    };
    var dataH = [traceH];
    Plotly.newPlot('myDiv', dataH,layoutH);

    var minc = minv
    var maxc = 3
    var size = (maxc - minc)/10
    var zero_frac = 0.001    
    var cs = []
    if (minc < 0){
        zero_frac = (0 - minc) / (maxc-minc)
        var lev1 = zero_frac + 0.1*(1-zero_frac)
        var lev2 = zero_frac + 0.3*(1-zero_frac)
        var lev3 = zero_frac + 0.5*(1-zero_frac)
        cs =  [[0,'RosyBrown'],[String(zero_frac+0.001),'AliceBlue'],[String(lev1),'LightBlue'],[String(lev2),'CornflowerBlue'],[String(lev3),'Crimson'],[1,'rgb(100, 0, 0)']]
    }
    else{
        cs =  [[0,'AliceBlue'],[0.25,'LightBlue'],[0.5,'CornflowerBlue'],[0.75,'Crimson'],[1,'rgb(100, 0, 0)']]
    }
    cs =  [[0,'AliceBlue'],[0.25,'LightBlue'],[0.5,'CornflowerBlue'],[0.75,'Crimson'],[1,'rgb(100, 0, 0)']]
    
    
    var data = [ {
		z: jv,
		x: jx,
		y: jy,
		type: 'contour',
        colorscale: cs,
        reversescale : false,
        autocontour: false,
        line : {
            width:0.5,            
            color:'DimGray'
        },
        contours: {
            start: minc,
            end: maxc,
            size: size            
        }	    
    }];

    var layout = {
        autosize: true,
        title: 'Contour plot of electron density plane',
        xaxis: {        
        showgrid: false,
        zeroline: false
        },
        yaxis: {
        scaleanchor: 'x',
        scaleratio: 1
        }
    };
    
    Plotly.newPlot('myCountour', data,layout);
</script>