Leucippus/Controllers/CompareController.cs
using Leucippus.Models;
using LeuciShared;
using Microsoft.AspNetCore.Mvc;

namespace Leucippus.Controllers
{
    public class CompareController : Controller
    {
        public async Task<IActionResult> Index
        (
            string activetab = "tA",
            string mode = "CALC",
            string pdbcodeA = "1ejg",
            string pdbcodeB = "3nir",
            double width = 6,
            int samples = 100,
            string interp = "LINEAR",
            string matrix = "DENSITY",
            double fosA = 2,
            double fcsA = -1,
            double fosB = 2,
            double fcsB = -1,
            string nav = "",
            string c_xyzA = "", string l_xyzA = "", string p_xyzA = "",string caA = "", string laA = "", string paA = "",
            string c_xyzB = "", string l_xyzB = "", string p_xyzB = "", string caB = "", string laB = "", string paB = "",
            string xAxis = "",
            string yAxis = "",
            string slicedensityA = "",
            string slicedensityB = "",
            string slicedensityD = "",
            double minDA = 0, double minLA = 0, double maxDA = 0, double maxLA = 0,
            double minDB = 0, double minLB = 0, double maxDB = 0, double maxLB = 0,
            double minDD = 0, double minLD = 0, double maxDD = 0, double maxLD = 0,
           // visual elements
           string floorA = "100", string capA = "100", string hueA = "Best", string cbarA = "Y", string plotA = "heatmap",
           string floorB = "100", string capB = "100", string hueB = "Best", string cbarB = "Y", string plotB = "heatmap",
           string floorD = "100", string capD = "100", string hueD = "Best", string cbarD = "Y", string plotD = "heatmap"
        )
        {
            //get any data to display
            ViewBag.PdbCodeA = pdbcodeA;
            ViewBag.PdbCodeB = pdbcodeB;
            ViewBag.Width = width;
            ViewBag.Samples = samples;
            ViewBag.Interp = interp;
            ViewBag.Matrix = matrix;
            ViewBag.FosA = fosA;
            ViewBag.FcsA = fcsA;
            ViewBag.FosB = fosB;
            ViewBag.FcsB = fcsB;

            SinglePosition sliceA = SinglePosition.makeFromFlat(xAxis, yAxis, slicedensityA, slicedensityA, slicedensityA, minDA, maxDA, minLA, maxLA, floorA, capA, hueA, cbarA,plotA);
            SinglePosition sliceB = SinglePosition.makeFromFlat(xAxis, yAxis, slicedensityB, slicedensityB, slicedensityB, minDB, maxDB, minLB, maxLB, floorB, capB, hueB, cbarB, plotB);
            SinglePosition sliceD = SinglePosition.makeFromFlat(xAxis, yAxis, slicedensityD, slicedensityD, slicedensityD, minDD, maxDD, minLD, maxLD, floorD, capD, hueD, cbarD, plotD);

            sliceD.matricesDiff(sliceA, sliceB);
            

            ViewBag.SliceA = sliceA;
            ViewBag.SliceB = sliceB;
            ViewBag.SliceD = sliceD;

            // Tab defaults
            ViewBag.ActiveTab = activetab;
            ViewBag.ColorA = "black";
            ViewBag.ColorB = "black";
            ViewBag.ColorO = "black";
            ViewBag.DisplayA = "none";
            ViewBag.DisplayB = "none";
            ViewBag.DisplayO = "none";
            if (activetab == "tA")
            {
                ViewBag.ColorA = "crimson";
                ViewBag.DisplayA = "block";
            }
            else if (activetab == "tB")
            {
                ViewBag.ColorB = "crimson";
                ViewBag.DisplayB = "block";
            }
            else if (activetab == "tO")
            {
                ViewBag.ColorO = "crimson";
                ViewBag.DisplayO = "block";
            }
            if (nav != "ABC" && nav != "" && nav.Contains(":"))
            {
                string[] navs = nav.Split(":");
                if (navs[0] == "A")
                    applyNav(navs[1], pdbcodeA);
                else
                    applyNav(navs[1], pdbcodeB);
            }
            else if (mode == "CALC")
            {
                await applyRefresh(pdbcodeA, interp, fosA, fcsA, width, samples);
                DensityMatrix dmA = await DensitySingleton.Instance.getMatrix(pdbcodeA, interp, fosA, fcsA, 3);                                
                ViewBag.SliceA = dmA.getSinglePosition();
                ViewBag.SliceA.addVisual(sliceA);

                await applyRefresh(pdbcodeB, interp, fosB, fcsB, width, samples);
                DensityMatrix dmB = await DensitySingleton.Instance.getMatrix(pdbcodeB, interp, fosB, fcsB, 3);
                ViewBag.SliceB = dmB.getSinglePosition();
                ViewBag.SliceB.addVisual(sliceB);

                ViewBag.SliceD = Helper.singlePosDiff(ViewBag.SliceA,ViewBag.SliceB);
                ViewBag.SliceD.addVisual(sliceD);
            }

            

            // return any defaults
            ViewBag.Mode = "CALC";
            ViewBag.Nav = "ABC";
            return View();
        }

        public void applyNav(string nav, string pdbcode)
        {

        }
        public async Task applyRefresh(string pdbcode, string interp, double fos, double fcs, double width, int samples)
        {
            if (DensitySingleton.Instance.needMatrix(pdbcode))
            {
                bool ok = await MatrixHelper.loadFDFiles(pdbcode);                
            }
            DensityMatrix dm = await DensitySingleton.Instance.getMatrix(pdbcode, interp, fos, fcs, 3);

            string[] first3 = DensitySingleton.Instance.FD.PA.getFirstThreeCoords();
            VectorThree cAtom = DensitySingleton.Instance.FD.PA.getCoords(first3[0]);
            VectorThree lAtom = DensitySingleton.Instance.FD.PA.getCoords(first3[1]);
            VectorThree pAtom = DensitySingleton.Instance.FD.PA.getCoords(first3[2]);


            dm.create_scratch_slice(width, samples, true, 
                    cAtom, lAtom, pAtom,
                    cAtom, lAtom, pAtom,
                    DensitySingleton.Instance.FD.PA, -1, -1
                    );


        }
    }

    
}

Leucippus/Controllers/SuperController.cs
using Leucippus.Models;
using LeuciShared;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq.Expressions;
using System.Reflection.PortableExecutable;

namespace Leucippus.Controllers
{
    public class SuperController : Controller
    {       
        public async Task<IActionResult> Index(            
            string update = "N",
            string motif = "{atom:C}{atom:CA,offset:0}{atom:O,offset:0}",
            string pdbcodes = "6eex",                 
            int fos = 2,
            int fcs = -1,
            double width = 6, 
            int samples = 100,
            string interp = "LINEAR",            
            string exclusions = "A:1,A:2",
            string inclusions = null)
        {
            ViewBag.Error = "";
            //ViewBag.Matches = "";
            //ViewBag.Lines = "";
            //ViewBag.Distances = "";

            ViewBag.DensitySlices = new List<double[][]>();
            ViewBag.DensityNames = new List<string>();
            ViewBag.SinglePositions = new List<SinglePosition>();
            ViewBag.SingleMatches = new List<SingleMatches>();

            SinglePosition superP = new SinglePosition();
                        
            string[] pdbcodelist = pdbcodes.Split(",");
            List<string[]> match_motif = new List<string[]>();
            List<string> pdbcodesgood = new List<string>();
            if (update.Contains("Y"))
            {                
                foreach (var pdbcod in pdbcodelist)
                {
                    try
                    {
                        string pdbcode = pdbcod.ToLower();
                        bool ok = await DensitySingleton.Instance.loadFDFiles(pdbcode);
                        DensityMatrix dm = await DensitySingleton.Instance.getMatrix(pdbcode, interp, fos, fcs, 2, true);
                        List<Atom[]> atoms_motif;
                        List<double[]> dis_motif;
                        List<VectorThree[]> coords_motif;
                        match_motif = DensitySingleton.Instance.FD.PA.getMatchesMotif(motif, out dis_motif, out atoms_motif);
                        for (int i = 0; i < match_motif.Count; ++i)
                        {
                            string[] mms = match_motif[i];
                            Atom[] ats = atoms_motif[i];
                            double[] diss = dis_motif[i];
                            SingleMatches sms = new SingleMatches();
                            for (int j = 0; j < ats.Length; ++j)
                            {
                                SingleMatch sm = new SingleMatch(pdbcode, ats[j].Line, Convert.ToString(Math.Round(diss[j], 4)), mms[j]);
                                sms.singleMatches.Add(sm);
                            }
                            ViewBag.SingleMatches.Add(sms);


                            //foreach (var m in mm)
                            //    ViewBag.Matches += m + "\n";
                            //ViewBag.Matches += "\n";
                        }
                        pdbcodesgood.Add(pdbcode);
                    }
                    catch (Exception e)
                    {
                        ViewBag.Error += pdbcod + " - " + e.Message + "<br/>";
                    }
                    

                    /*foreach (var al in atoms_motif)
                    {
                        foreach (var a in al)
                            ViewBag.Lines += pdbcode + ":" + a.Line + "\n";
                        ViewBag.Lines += "\n";
                    }

                    foreach (var dd in dis_motif)
                    {
                        foreach (var d in dd)
                            ViewBag.Distances += Convert.ToString(Math.Round(d, 4)) + "\n";
                        ViewBag.Distances += "\n";
                    }*/
                }
            }
            if (update.Contains("C"))
            {
                double[][]? sliceDensity = null;
                double[][]? sliceRadient = null;
                double[][]? sliceLaplacian = null;

                double minV = 1000;
                double maxV = -1000;
                double minL = 1000;
                double maxL = -1000;

                foreach (var pdbcode in pdbcodesgood)
                {
                    bool ok = await DensitySingleton.Instance.loadFDFiles(pdbcode);
                    DensityMatrix dm = await DensitySingleton.Instance.getMatrix(pdbcode, interp, fos, fcs,2);
                    //List<VectorThree[]> match_coords = new List<VectorThree[]>();
                    List<Atom[]> match_atoms = new List<Atom[]>();
                    List<double[]> match_disses = new List<double[]>();
                    match_motif = DensitySingleton.Instance.FD.PA.getMatchesMotif(motif, out match_disses,out match_atoms);
                    //match_motif = DensitySingleton.Instance.FD.PA.getMatchMotif(motif, exclusions, inclusions, out match_coords, out lines);
                    
                    
                    

                    // create each matrix
                    foreach (Atom[] atoms in match_atoms) //we are taking the first 3 as being central linear planar
                    {
                        VectorThree coordC = atoms[0].coords();
                        VectorThree coordL = atoms[1].coords();
                        VectorThree coordP = atoms[2].coords();
                        
                        SinglePosition singleP = new SinglePosition();
                        dm.create_scratch_slice(width, samples,  true, 
                            coordC, coordL, coordP,
                            coordC, coordL, coordP,
                            DensitySingleton.Instance.FD.PA, -1, -1);

                        ViewBag.DensitySlices.Add(dm.SliceDensity);
                        ViewBag.DensityNames.Add("Density" + Convert.ToString(ViewBag.DensitySlices.Count));                        
                        // The superpositions have the same axis
                        superP.xAxis = dm.SliceAxis;
                        superP.yAxis = dm.SliceAxis;

                        // the single positions are saved individually
                        singleP.description = pdbcode + " Central=" + atoms[0].Summary + " Linear=" + atoms[1].Summary + " Planar=" + atoms[2].Summary;
                        singleP.xAxis = dm.SliceAxis;
                        singleP.yAxis = dm.SliceAxis;
                        singleP.copyDensity(dm.SliceDensity);
                        singleP.copyRadient(dm.SliceRadient);
                        singleP.copyLaplacian(dm.SliceLaplacian);                        
                        singleP.minD = dm.DMin;
                        singleP.maxD = dm.DMax;
                        singleP.minL = dm.LMin;
                        singleP.maxL = dm.LMax;
                        singleP.contourDen = "SinglePosition" + Convert.ToString(ViewBag.SinglePositions.Count+1) + "DEN";
                        singleP.contourRad = "SinglePosition" + Convert.ToString(ViewBag.SinglePositions.Count + 1) + "RAD";
                        singleP.contourLap = "SinglePosition" + Convert.ToString(ViewBag.SinglePositions.Count + 1) + "LAP";
                        ViewBag.SinglePositions.Add(singleP);

                        if (sliceDensity == null)
                        {
                            sliceDensity = dm.SliceDensity;
                            sliceRadient = dm.SliceRadient;
                            sliceLaplacian = dm.SliceLaplacian;
                            minV = dm.DMin;
                            maxV = dm.DMax;
                            minL = dm.LMin;
                            maxL = dm.LMax;
                        }
                        else
                        {
                            for (int i = 0; i < sliceDensity.Length; i++)
                            {
                                for (int j = 0; j < sliceDensity[i].Length; j++)
                                {
                                    sliceDensity[i][j] += dm.SliceDensity[i][j];
                                    maxV = Math.Max(maxV, sliceDensity[i][j]);
                                    minV = Math.Min(minV, sliceDensity[i][j]);

                                    if (sliceRadient.Length == sliceDensity.Length)
                                        sliceRadient[i][j] += dm.SliceRadient[i][j];

                                    if (sliceLaplacian.Length == sliceDensity.Length)
                                    {
                                        sliceLaplacian[i][j] += dm.SliceLaplacian[i][j];
                                        maxL = Math.Max(maxL, sliceLaplacian[i][j]);
                                        minL = Math.Min(minL, sliceLaplacian[i][j]);
                                    }
                                }
                            }
                        }
                    }                    
                }
                // matrix
                //ViewBag.SliceDensity = sliceDensity;
                //ViewBag.SliceRadient = sliceRadient;
                //ViewBag.SliceLaplacian = sliceLaplacian;

                //ViewBag.MinV = minV;
                //ViewBag.MaxV = maxV;
                //ViewBag.MinL = minL;
                //ViewBag.MaxL = maxL;
                superP.densityMatrix = sliceDensity;
                superP.radientMatrix = sliceRadient;
                superP.laplacianMatrix = sliceLaplacian;
                superP.minD = minV;
                superP.maxD = maxV;
                superP.minL = minL;
                superP.maxL = maxL;
                superP.contourDen = "SuperPositionDEN";
                superP.contourRad = "SuperPositionRAD";
                superP.contourLap = "SuperPositionLAP";
                ViewBag.SuperPosition = superP;
            }

            // View items            
            ViewBag.PdbCodes = pdbcodes;

Leucippus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Leucippus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Leucippus.styles.css" asp-append-version="true" />    
    <link rel="icon" href="~/images/favicon.ico" type="image/x-icon">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Leucippus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between"><!-- style="background-color:Crimson;color:AliceBlue;">-->
                    <ul class="navbar-nav flex-grow-1">                        
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Matrix" asp-action="Browse">Explore</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Compare" asp-action="Index">Compare</a>
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Super" asp-action="Index">Superposition</a>
                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Help">Help</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Rachel Alcraft, 2022 <a asp-area="" asp-controller="Home" asp-action="Index">Home</a> - <a asp-area="" asp-controller="Home" asp-action="About">About</a> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> Supervisor Mark A Williams, Birkbeck (Univeristy of London)
        </div>        
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Leucippus/Views/Shared/_LayoutDensity.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Leucippus</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Leucippus.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/images/favicon.ico" type="image/x-icon">
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>    
    <link href="nouislider.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Leucippus</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <!-- style="background-color:Crimson;color:AliceBlue;">-->
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">                            
                            <a class="nav-link text-light" asp-area="" asp-controller="Matrix" asp-action="Browse">Explore</a>                                                                                    
                        </li>
                        <!--<li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Super" asp-action="Index">Superposition</a>
                        </li>-->
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Compare" asp-action="Index">Compare</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="About">About</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Help">Help</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; Rachel Alcraft, 2022 <a asp-area="" asp-controller="Home" asp-action="Index">Home</a> - <a asp-area="" asp-controller="Home" asp-action="About">About</a> - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> Supervisor Mark A Williams, Birkbeck (Univeristy of London)
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>